version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - set -e
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382834514.dkr.ecr.us-east-1.amazonaws.com
      - docker login --username myaswrepo --password 'Monitor11!'
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t backend:latest .
      - docker tag backend:latest 992382834514.dkr.ecr.us-east-1.amazonaws.com/backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 992382834514.dkr.ecr.us-east-1.amazonaws.com/backend:latest
      
      