# Generated by Django 5.0.3 on 2024-08-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_remove_coursematerials_course_remove_courses_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='backend_app.course'),
        ),
    ]
