# Generated by Django 5.0.3 on 2024-08-18 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_myuser_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='enrolled_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
