# Generated by Django 5.0.3 on 2024-08-18 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_remove_myuser_enrolled_courses_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
