# Generated by Django 5.0.3 on 2024-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='Write a short description about the course...', max_length=500),
        ),
    ]
