# Generated by Django 5.0.3 on 2024-09-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_announcement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='user',
        ),
    ]
