# Generated by Django 5.0.3 on 2024-09-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_alter_tasksubmission_unique_together_taskassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='student',
        ),
        migrations.RemoveField(
            model_name='portfolioentry',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='InvitationToken',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioEntry',
        ),
    ]
