# Generated by Django 5.0.3 on 2024-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_delete_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='late_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='personal_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
