# Generated by Django 5.0.3 on 2024-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_taskassignment_is_late_taskassignment_late_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='personal_notes',
            new_name='student_personal_notes',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='teacher_feedback',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
