# Generated by Django 5.0.3 on 2024-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0021_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(default=1, upload_to='submissions/'),
            preserve_default=False,
        ),
    ]
