# Generated by Django 5.0.3 on 2024-10-22 19:23

import backend_app.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_submissionfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionfile',
            name='s3_bucket_key',
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(upload_to=backend_app.services.user_submission_directory_path),
        ),
    ]
