# Generated by Django 5.0.3 on 2024-10-24 14:47

import backend_app.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_myuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfile',
            name='s3_bucket_key',
        ),
        migrations.AddField(
            model_name='taskfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend_app.services.task_files_directory_path),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend_app.services.user_submission_directory_path),
        ),
    ]
