# Generated by Django 5.0.3 on 2024-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_remove_taskfile_s3_bucket_key_taskfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
