# Generated by Django 5.0.3 on 2024-11-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_alter_taskassignment_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
